version: '2'
services:
  web:
    image: nginx:1.11
    container_name: web_projectname
    restart: always
    ports:
        - "8080:80"
    volumes:
        - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf

        - ./logs/nginx:/var/log/nginx
        - ./www:/www
    links:
        - php

  php:
    build: ./docker/php
    container_name: php_projectname
    restart: always
    depends_on:
        - db
    links:
        - db
    volumes:
        - ./docker/php/php-dev.ini:/usr/local/etc/php/php.ini
        - ./docker/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
        - ./docker/php/supervisor/conf.d:/etc/supervisor/conf.d
        - ./www:/www

  db:
    image: mysql:5.7.12
    container_name: db_projectname
    restart: always
#    ports:
#        - "33060:3306"
    volumes:
        - /var/db/projectname:/var/lib/mysql
        - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
        - ./docker/mysql/mysql.sh:/root/mysql.sh
    environment:
        MYSQL_ROOT_PASSWORD: sa4djhDjsdErwhecdsd8sD
        MYSQL_USER: user
        MYSQL_PASSWORD: sa4djhDjhecdsd8sD
        MYSQL_DATABASE: app

  phpmyadmin:
      build: ./docker/phpmyadmin/
      restart: always
      links:
          - db
      ports:
          - "8081:80"
      environment:
         - MYSQL_HOST=db
  sphinx:
    build: ./docker/sphinx
    container_name: sphinx_projectname
    depends_on:
        - db
    links:
        - db
    restart: always
    volumes:
        - ./docker/sphinx/sphinx.conf:/etc/sphinxsearch/sphinx.conf
    environment:
        SPHINX_MODE: indexing


#export TERM=xterm
#export COMPOSE_API_VERSION=1.18