version: '2'
services:
  web:
    image: nginx:1.10
    restart: always
    ports:
        - "8080:80"
    volumes:
        - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf

        - ./logs/nginx:/var/log/nginx
        - ./www:/www
    links:
        - php
  php:
    build: ./docker/php
    restart: always
    depends_on:
        - db
    links:
        - db
    volumes:
        - ./docker/php/php-dev.ini:/usr/local/etc/php/php.ini
        - ./docker/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
        - ./docker/php/supervisor/conf.d:/etc/supervisor/conf.d
        - ./www:/www
  db:
    image: mysql:5.7
    restart: always
#    ports:
#        - "33060:3306"
    volumes:
        - /var/db/projectname:/var/lib/mysql
        - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_USER: user
        MYSQL_PASSWORD: password
        MYSQL_DATABASE: app
  sphinx:
    build: ./docker/sphinx
    depends_on:
        - db
    links:
        - db
    restart: always
    volumes:
        - ./docker/sphinx/sphinx.conf:/etc/sphinxsearch/sphinx.conf
    environment:
        SPHINX_MODE: indexing


#export TERM=xterm
#export COMPOSE_API_VERSION=1.18